---
title: "Zachowowania na COVID-19 "
author: "Krzysztof Łupkowski"
date: "5 06 2021"
output:
  html_document:
    toc: true
    df_print: paged
  md_document:
    toc: true
    variant: markdown_github
---
## 1. Wstęp

Na COVID-19 zachorowało 224 mężczyzn i 151 kobiet.

## 2. Kod wyliczający wykorzystane biblioteki

```{r, echo = FALSE, message = FALSE}

library(ggplot2)
library(dplyr)
library(datasets)
library(lattice)
library(ggplot2)
library(openxlsx)


```

```{r}
info <- sessionInfo()
print(info, RNG = FALSE , locale = FALSE, packages=TRUE)

```


## 3. Kod pozwalający wczytać dane z pliku

```{r}
dane <- read.xlsx("wuhan_blood_sample_data_Jan_Feb_2020.xlsx")

head(dane)

```


## 4. Sekcję podsumowującą rozmiar zbioru i podstawowe statystyki

Rozmiar zbioru:
```{r, echo = FALSE, message = FALSE}
dim(dane)


```

## 5. Analiza tabelaryczna

Wyodrębniono część tabeli, bez badań

```{r}
dane2 <- select(filter(dane, !is.na(PATIENT_ID)), 1, 3:4, 7)

dane2

```


Tabela prezentuje zachorowalność u mężczyzn (1) i kobiet(2) w badanej populacji

```{r, echo = FALSE, message = FALSE}
tabela1 <- dane2 %>%
                group_by(gender) %>%
                summarize(płesć_suma = n())
tabela1
```



